KilometroZero7/Controllers/UserAdminController.cs
using KilometroZero7.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KilometroZero7.Controllers
{
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            ViewBag.UtentiCount = UserManager.Users.Count();
            return View(await UserManager.Users.ToListAsync());
        }

        // GET: /Users/IndexCom
        [Authorize(Roles = "Comune")]
        public async Task<ActionResult> IndexCom()
        {
            ViewBag.UtentiCount = UserManager.Users.Where(c => c.ComuneId == 1).Count();
            return View(await UserManager.Users.Where(c=>c.ComuneId== 1).ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/DetailsComm/5
        [Authorize(Roles = "Commerciante")]
        public async Task<ActionResult> DetailsComm()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }


        //
        // GET: /Users/Create
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Nome = user.Nome,
                Cognome = user.Cognome,
                PartitaIva = user.PartitaIva,
                Telefono = user.Telefono,
                Indirizzo = user.Indirizzo,
                CAP = user.CAP,
                RagioneSociale = user.RagioneSociale,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,Nome,Cognome,PartitaIva,Telefono,Indirizzo,CAP,ComuneId,RagioneSociale")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.Nome = editUser.Nome;
                user.Cognome = editUser.Cognome;
                user.Cognome = editUser.Cognome;
                user.PartitaIva = editUser.PartitaIva;
                user.Telefono = editUser.Telefono;
                user.Indirizzo = editUser.Indirizzo;
                user.CAP = editUser.CAP;
                user.RagioneSociale = editUser.RagioneSociale;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }
        //
        // GET: /users/EditComm/5
        [Authorize(Roles = "Commerciante")]
        public async Task<ActionResult> EditComm()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditCommViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Nome = user.Nome,
                Cognome = user.Cognome,
                PartitaIva = user.PartitaIva,
                Telefono = user.Telefono,
                Indirizzo = user.Indirizzo,
                CAP = user.CAP,
                RagioneSociale = user.RagioneSociale,
            });
        }
        //
        // POST: /Users/EditComm/5
        [Authorize(Roles = "Commerciante")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditComm([Bind(Include = "Email,Id,Nome,Cognome,PartitaIva,Telefono,Indirizzo,CAP,RagioneSociale")] EditCommViewModel editUser)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.Nome = editUser.Nome;
                user.Cognome = editUser.Cognome;
                user.PartitaIva = editUser.PartitaIva;
                user.Telefono = editUser.Telefono;
                user.Indirizzo = editUser.Indirizzo;
                user.CAP = editUser.CAP;
                user.Cognome = editUser.Cognome;
                user.RagioneSociale = editUser.RagioneSociale;
                await UserManager.UpdateAsync(user);
                return RedirectToAction("DetailsComm");
            }
            ModelState.AddModelError("", "Something failed.");
            return View("Index");
        }


        //
        // GET: /Users/Delete/5

KilometroZero7/Views/UsersAdmin/Create.cshtml
@model KilometroZero7.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KilometroZero7/Views/UsersAdmin/Delete.cshtml
@model KilometroZero7.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete.</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <h4>User.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KilometroZero7/Views/UsersAdmin/Details.cshtml
@model KilometroZero7.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details.</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cognome)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RagioneSociale)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RagioneSociale)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PartitaIva)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartitaIva)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Indirizzo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Indirizzo)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CAP)
        </dd>
    </dl>
</div>
<h4>Ruoli di appartenenza</h4>
@Html.Display(User.Identity.Name.ToString()) 
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>Nessun ruolo assegnato a questo utente</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Torna alla lista", "Index")
</p>

KilometroZero7/Views/UsersAdmin/DetailsComm.cshtml
@model KilometroZero7.Models.ApplicationUser

@{
    ViewBag.Title = "DetailsComm";
}

<h2>Profilo commerciante</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cognome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cognome)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PartitaIva)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartitaIva)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Indirizzo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Indirizzo)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CAP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CAP)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RagioneSociale)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RagioneSociale)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Ruoli di appartenenza
        </dt>
        <dd>
            @if (ViewBag.RoleNames.Count == 0)
            {
                <hr />
                <p>Nessun ruolo assegnato a questo utente</p>
            }
            @foreach (var item in ViewBag.RoleNames)
            {
                <span>@item</span>
            }
            
        </dd>
    </dl>
</div>

<hr/>
<div>
    <span class="btn btn-default">
        @Html.ActionLink("Modifica", "EditComm")
    </span>
</div>

KilometroZero7/Views/UsersAdmin/Edit.cshtml
@model KilometroZero7.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit User Form.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Roles", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" })
                }
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KilometroZero7/Views/UsersAdmin/EditComm.cshtml
@model KilometroZero7.Models.EditCommViewModel

@{
    ViewBag.Title = "EditComm";
}

<h2>Modifica profilo</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.LabelFor(m => m.Email, new { @class = "has-success control-label col-md-2" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nome)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cognome)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PartitaIva, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.PartitaIva, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PartitaIva)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Telefono, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Telefono)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Indirizzo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Indirizzo, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Indirizzo)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CAP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.CAP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CAP)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RagioneSociale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.RagioneSociale, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RagioneSociale)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                <span class="btn btn-default">@Html.ActionLink("Annulla", "DetailsComm")</span>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna al profilo", "DetailsComm")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KilometroZero7/Views/UsersAdmin/Index.cshtml
@model IEnumerable<KilometroZero7.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)


        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cognome)


        </th>
        <th>
            @Html.DisplayNameFor(model => model.Indirizzo)


        </th>
   </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Indirizzo)


            </td>
          <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

KilometroZero7/Views/UsersAdmin/IndexCom.cshtml
@model IEnumerable<KilometroZero7.Models.ApplicationUser>

@{
    ViewBag.Title = "IndexCom";
}

<h2>IndexCom</h2>

<p>
    <a href="~/UsersAdmin/Create" class="btn btn-primary"><span class="badge">@ViewBag.UtentiCount</span> Nuovo</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)


        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cognome)


        </th>
        <th>
            @Html.DisplayNameFor(model => model.Indirizzo)


        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Indirizzo)


            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>