KilometroZero7/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KilometroZero7.Models;

namespace KilometroZero7.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        public ActionResult Index()
        {
            ViewBag.CategorieCount = db.Categories.Count();
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "categoria_id,nome_categoria")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categorie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categorie);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categories/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "categoria_id,nome_categoria")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categorie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categorie);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categorie categorie = db.Categories.Find(id);
            db.Categories.Remove(categorie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KilometroZero7/Controllers/ComunisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KilometroZero7.Models;

namespace KilometroZero7.Controllers
{
    public class ComunisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comunis
        public ActionResult Index()
        {
            ViewBag.ComuniCount = db.Comunis.Count();
            return View(db.Comunis.ToList());
        }

        // GET: Comunis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comuni comuni = db.Comunis.Find(id);
            if (comuni == null)
            {
                return HttpNotFound();
            }
            return View(comuni);
        }

        // GET: Comunis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comunis/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ComuneId,NomeRiferimento,TelRiferimento,Comune,Provincia,Regione")] Comuni comuni)
        {
            if (ModelState.IsValid)
            {
                db.Comunis.Add(comuni);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comuni);
        }

        // GET: Comunis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comuni comuni = db.Comunis.Find(id);
            if (comuni == null)
            {
                return HttpNotFound();
            }
            return View(comuni);
        }

        // POST: Comunis/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ComuneId,NomeRiferimento,TelRiferimento,Comune,Provincia,Regione")] Comuni comuni)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comuni).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comuni);
        }

        // GET: Comunis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comuni comuni = db.Comunis.Find(id);
            if (comuni == null)
            {
                return HttpNotFound();
            }
            return View(comuni);
        }

        // POST: Comunis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comuni comuni = db.Comunis.Find(id);
            db.Comunis.Remove(comuni);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KilometroZero7/Controllers/ProdottisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KilometroZero7.Models;
using Microsoft.AspNet.Identity;

namespace KilometroZero7.Controllers
{
    public class ProdottisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Prodottis
        public ActionResult Index()
        {
            if (User.IsInRole("Commerciante"))
            {
            var utente = User.Identity.GetUserId();
            var prodottis = db.Prodottis.Include(p => p.nome_categoria).Where(p=>p.utente.Id == utente);
            ViewBag.ProdottiCount = prodottis.Count();
            return View(prodottis.ToList());
            }
            else
            {
                if (User.IsInRole("Admin"))
                {
                    var prodottis = db.Prodottis.Include(p => p.nome_categoria);
                    ViewBag.ProdottiCount = prodottis.Count();
                    return View(prodottis.ToList());
                }
            }
            return View();
        }

        // GET: Prodottis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodottis.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            return View(prodotti);
        }

        // GET: Prodottis/Create
        public ActionResult Create()
        {
            ViewBag.categoria_Id = new SelectList(db.Categories, "categoria_id", "nome_categoria");
            return View();
        }

        // POST: Prodottis/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "prodotto_id,attivo,nome_prodotto,descrizione_prodotto,prezzo_prodotto,categoria_Id")] Prodotti prodotti)
        {
            if (ModelState.IsValid)
            {
                var CurrentUMUser = User.Identity.GetUserId();
                var CurrenUser = db.Users.Find(CurrentUMUser);
                prodotti.utente = CurrenUser;
                db.Prodottis.Add(prodotti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoria_Id = new SelectList(db.Categories, "categoria_id", "nome_categoria", prodotti.categoria_Id);
            return View(prodotti);
        }

        // GET: Prodottis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodottis.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoria_Id = new SelectList(db.Categories, "categoria_id", "nome_categoria", prodotti.categoria_Id);
            return View(prodotti);
        }

        // POST: Prodottis/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "prodotto_id,attivo,nome_prodotto,descrizione_prodotto,prezzo_prodotto,categoria_Id")] Prodotti prodotti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prodotti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoria_Id = new SelectList(db.Categories, "categoria_id", "nome_categoria", prodotti.categoria_Id);
            return View(prodotti);
        }

        // GET: Prodottis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodottis.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            return View(prodotti);
        }

        // POST: Prodottis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prodotti prodotti = db.Prodottis.Find(id);
            db.Prodottis.Remove(prodotti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KilometroZero7/Views/Shared/_CercaPartial.cshtml
@{
    ViewBag.Title = "KilometroZero";
    var bkg = ViewBag.Title + "_s.jpg";}
<div class="jumbotron" style="background-image:url(/Content/Images/@bkg)">
    <div class="row">
        <div class="col-md-6 text-center">
            <h1><span class="red">K</span>ilometro <span class="red">Z</span>ero</h1>
        </div>
        <div class="col-md-6 box1">
            <h3 class="white">
                In che paese ti trovi?<br />
            </h3>
            <h3>
                Che cosa stai cercando?<br />
            </h3>
            <div class="btn btn-primary">Trova</div>
            @*<img class="img-responsive" src="/Content/Images/CaravaggioLente.jpg" />*@
        </div>
    </div>
</div>

KilometroZero7/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index"><span class="red">K</span>ilometro <span class="red">Z</span>ero</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Home/Index">Home</a>
                    <li>@Html.ActionLink("Principio", "Principio", "Home")</li>
                    <li>@Html.ActionLink("Commercianti", "Commercianti", "Home")</li>
                    <li>@Html.ActionLink("Comuni", "Comuni", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                    <li>
                        <a href="#" title="Pannelo controllo"><span class="glyphicon glyphicon-cog" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></span></a>
                    </li>
                    }
                 </ul>
                @Html.Partial("_LoginPartial")
            </div>
                <div  class="navbar-collapse collapse">
                    <ul class="nav navbar-nav collapse" id="collapseExample">

                        @if (Request.IsAuthenticated && !User.IsInRole("Admin") && !User.IsInRole("Commerciante") && !User.IsInRole("Comune"))
                        {
                                <li>@Html.ActionLink("Profilo", "Index", "RolesAdmin")</li>
                        }


                        @if (Request.IsAuthenticated && User.IsInRole("Commerciante"))
                        {
                                    <li>
                                        <a href="/Prodottis/Index">Prodotti</a>
                                    </li>
                                    <li>@Html.ActionLink("Profilo", "DetailsComm", "UsersAdmin")</li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Comune"))
                        {
                                    <li>@Html.ActionLink("Gestisci commercianti", "IndexCom", "UsersAdmin")</li>
                        }
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                <li>@Html.ActionLink("Categorie", "Index", "Categories")</li>
                                <li>@Html.ActionLink("Prodotti", "Index", "Prodottis")</li>
                                <li>@Html.ActionLink("Comuni", "Index", "Comunis")</li>
                        }
                    </ul>
                </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <span>&copy; @DateTime.Now.Year - KilometroZero - <span class="almishCesare"><a href="http://www.cr-consult.eu/zona-web">Almish<b>&</b>Cesàre<b>W</b>eb</a></span></span>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>